alias t := train
alias r := run

VENV := ".venv"
PYTHON := VENV / "bin" / "python"

_default:
    @just --list

# install dependencies
deps:
    @source venv_setup.sh

# train model
train *ARGS='--save-model':
    {{PYTHON}} main.py {{ARGS}}

# run app
run *ARGS:
    {{PYTHON}} app.py {{ARGS}}

clean:
    rm -rf {{VENV}}